# Generated by Django 5.2.9 on 2025-12-26 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lead_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('project_name', models.CharField(db_index=True, max_length=200)),
                ('unit_type', models.CharField(db_index=True, max_length=50)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('visit_scheduled', 'Visit Scheduled'), ('visit_done_not_purchased', 'Visit Done Not Purchased'), ('purchased', 'Purchased'), ('not_interested', 'Not Interested')], db_index=True, max_length=50)),
                ('last_conversation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_conversation_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'indexes': [models.Index(fields=['project_name', 'lead_status'], name='leads_project_eee81f_idx'), models.Index(fields=['unit_type', 'lead_status'], name='leads_unit_ty_4b7da8_idx'), models.Index(fields=['last_conversation_date'], name='leads_last_co_0c89c0_idx')],
            },
        ),
    ]
